// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGiLIel51-t9z0VeSsSkSQgO3HZRn9R0I',
    appId: '1:666968801930:web:cada7a4fe61139c07a6373',
    messagingSenderId: '666968801930',
    projectId: 'movie-app-54bb7',
    authDomain: 'movie-app-54bb7.firebaseapp.com',
    storageBucket: 'movie-app-54bb7.firebasestorage.app',
    measurementId: 'G-4J48R4VJ1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCg5tr8Nl2d_PzuNa73DmyHXP-y8UXXk',
    appId: '1:666968801930:android:39e04b90a5a8e7577a6373',
    messagingSenderId: '666968801930',
    projectId: 'movie-app-54bb7',
    storageBucket: 'movie-app-54bb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6KEgNNdXb87x8UMLPIHrAPXGMIitLw4',
    appId: '1:666968801930:ios:7aff3c18262c319a7a6373',
    messagingSenderId: '666968801930',
    projectId: 'movie-app-54bb7',
    storageBucket: 'movie-app-54bb7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6KEgNNdXb87x8UMLPIHrAPXGMIitLw4',
    appId: '1:666968801930:ios:7aff3c18262c319a7a6373',
    messagingSenderId: '666968801930',
    projectId: 'movie-app-54bb7',
    storageBucket: 'movie-app-54bb7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGiLIel51-t9z0VeSsSkSQgO3HZRn9R0I',
    appId: '1:666968801930:web:957aa9ce7d3e24ce7a6373',
    messagingSenderId: '666968801930',
    projectId: 'movie-app-54bb7',
    authDomain: 'movie-app-54bb7.firebaseapp.com',
    storageBucket: 'movie-app-54bb7.firebasestorage.app',
    measurementId: 'G-XGN0K5KBNN',
  );
}
